package com.example.demo.controller;

import com.example.demo.model.Customer;
import com.example.demo.repository.CustomerRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping("test2")
public class Test2Controller {

    @Autowired
    private CustomerRepository customerRepository;

    @GetMapping
    public String getTest() {
        for(int i =0;i<1000;i++){
            Customer customer = new Customer();
            customer.setFirstName("test");
            customer.setTestString1("\n" +
                    "\n" +
                    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis eget tempus sem, at condimentum tellus. Quisque tempus pellentesque eros, ullamcorper scelerisque sem luctus quis. Suspendisse nunc lorem, faucibus et scelerisque et, gravida non diam. Sed vulputate a orci euismod consectetur. Integer cursus vulputate porttitor. Vestibulum tortor eros, volutpat vitae pretium a, commodo eu sapien. Sed eget maximus urna. Sed vel quam vitae justo blandit pellentesque. Aenean eu rhoncus arcu. Quisque finibus tellus nunc, quis rhoncus sapien faucibus interdum.\n" +
                    "\n" +
                    "Donec tincidunt diam tincidunt justo aliquam, ac tincidunt libero dignissim. Etiam eros nunc, rhoncus sit amet efficitur vitae, dictum eget mi. Vestibulum mollis augue nisl. Mauris nec fermentum nisi, quis porttitor nulla. Nullam iaculis erat quis quam molestie, non pharetra purus faucibus. Fusce faucibus laoreet placerat. Maecenas vel tortor commodo augue cursus consequat. Sed molestie, purus vel pulvinar ultrices, lorem quam pretium nibh, eu ultricies dolor lacus et tellus. Aenean vel est dapibus, laoreet nisi nec, lacinia ex. Praesent ut leo tincidunt, porttitor diam ut, blandit felis. In in viverra quam, non consequat nulla.\n" +
                    "\n" +
                    "Phasellus id venenatis elit. Proin convallis nisl sed nisl ornare, non lacinia mauris porttitor. Vivamus sit amet leo at purus eleifend efficitur et eu dui. Sed at finibus elit, at feugiat nibh. In tincidunt vulputate nunc, pretium porta purus scelerisque a. Aenean a nulla leo. Nam a diam sit amet massa malesuada blandit vitae a urna. Quisque malesuada arcu et velit faucibus consectetur. Integer quis elementum nibh. Fusce ut purus in lacus finibus sodales. Quisque tincidunt id ipsum sit amet sollicitudin. Pellentesque sapien lorem, facilisis et sem eget, ultrices varius nibh. Mauris sed vehicula est. Phasellus sed nunc non nibh tincidunt vestibulum.\n" +
                    "\n" +
                    "Sed semper metus sed ante porta semper. Donec tristique sed turpis nec varius. Cras cursus eros tellus, at laoreet ante euismod porta. Cras hendrerit turpis eget nisi rhoncus, vel maximus orci blandit. Vivamus auctor sit amet tellus sed vestibulum. Pellentesque mi elit, gravida et urna quis, luctus convallis enim. Nulla blandit ante ut nisl maximus dignissim. Praesent venenatis odio in nisi fringilla ullamcorper non nec nulla. Curabitur ullamcorper nulla quis nulla faucibus porta. Curabitur lacinia justo mauris, non tincidunt lacus rhoncus quis. Nam consequat tempor massa ac tincidunt. Aenean dapibus elit nec nibh fermentum, vitae ultricies quam bibendum. Mauris interdum sem vel tincidunt faucibus.\n" +
                    "\n" +
                    "Nullam nibh urna, fringilla non condimentum id, fringilla nec nisi. Donec luctus orci sed leo ornare luctus. Mauris lobortis nisl neque, non lobortis lorem lacinia at. Aliquam placerat id nunc ut scelerisque. Aliquam ultricies, tellus ac varius vehicula, ante mauris dapibus arcu, eget rutrum risus enim vitae dui. Ut aliquam est varius tempus tempus. Ut eleifend, felis dignissim dignissim placerat, nisl nulla faucibus nunc, eget maximus tortor augue ut arcu. Nulla tempus odio ac justo ultricies placerat. Duis a auctor quam, quis sagittis libero. Sed sollicitudin magna in venenatis faucibus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Ut porttitor nunc vel risus varius mollis. Suspendisse in laoreet quam. ");
            customer.setTestString2("L\n" +
                    "\n" +
                    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis eget tempus sem, at condimentum tellus. Quisque tempus pellentesque eros, ullamcorper scelerisque sem luctus quis. Suspendisse nunc lorem, faucibus et scelerisque et, gravida non diam. Sed vulputate a orci euismod consectetur. Integer cursus vulputate porttitor. Vestibulum tortor eros, volutpat vitae pretium a, commodo eu sapien. Sed eget maximus urna. Sed vel quam vitae justo blandit pellentesque. Aenean eu rhoncus arcu. Quisque finibus tellus nunc, quis rhoncus sapien faucibus interdum.\n" +
                    "\n" +
                    "Donec tincidunt diam tincidunt justo aliquam, ac tincidunt libero dignissim. Etiam eros nunc, rhoncus sit amet efficitur vitae, dictum eget mi. Vestibulum mollis augue nisl. Mauris nec fermentum nisi, quis porttitor nulla. Nullam iaculis erat quis quam molestie, non pharetra purus faucibus. Fusce faucibus laoreet placerat. Maecenas vel tortor commodo augue cursus consequat. Sed molestie, purus vel pulvinar ultrices, lorem quam pretium nibh, eu ultricies dolor lacus et tellus. Aenean vel est dapibus, laoreet nisi nec, lacinia ex. Praesent ut leo tincidunt, porttitor diam ut, blandit felis. In in viverra quam, non consequat nulla.\n" +
                    "\n" +
                    "Phasellus id venenatis elit. Proin convallis nisl sed nisl ornare, non lacinia mauris porttitor. Vivamus sit amet leo at purus eleifend efficitur et eu dui. Sed at finibus elit, at feugiat nibh. In tincidunt vulputate nunc, pretium porta purus scelerisque a. Aenean a nulla leo. Nam a diam sit amet massa malesuada blandit vitae a urna. Quisque malesuada arcu et velit faucibus consectetur. Integer quis elementum nibh. Fusce ut purus in lacus finibus sodales. Quisque tincidunt id ipsum sit amet sollicitudin. Pellentesque sapien lorem, facilisis et sem eget, ultrices varius nibh. Mauris sed vehicula est. Phasellus sed nunc non nibh tincidunt vestibulum.\n" +
                    "\n" +
                    "Sed semper metus sed ante porta semper. Donec tristique sed turpis nec varius. Cras cursus eros tellus, at laoreet ante euismod porta. Cras hendrerit turpis eget nisi rhoncus, vel maximus orci blandit. Vivamus auctor sit amet tellus sed vestibulum. Pellentesque mi elit, gravida et urna quis, luctus convallis enim. Nulla blandit ante ut nisl maximus dignissim. Praesent venenatis odio in nisi fringilla ullamcorper non nec nulla. Curabitur ullamcorper nulla quis nulla faucibus porta. Curabitur lacinia justo mauris, non tincidunt lacus rhoncus quis. Nam consequat tempor massa ac tincidunt. Aenean dapibus elit nec nibh fermentum, vitae ultricies quam bibendum. Mauris interdum sem vel tincidunt faucibus.\n" +
                    "\n" +
                    "Nullam nibh urna, fringilla non condimentum id, fringilla nec nisi. Donec luctus orci sed leo ornare luctus. Mauris lobortis nisl neque, non lobortis lorem lacinia at. Aliquam placerat id nunc ut scelerisque. Aliquam ultricies, tellus ac varius vehicula, ante mauris dapibus arcu, eget rutrum risus enim vitae dui. Ut aliquam est varius tempus tempus. Ut eleifend, felis dignissim dignissim placerat, nisl nulla faucibus nunc, eget maximus tortor augue ut arcu. Nulla tempus odio ac justo ultricies placerat. Duis a auctor quam, quis sagittis libero. Sed sollicitudin magna in venenatis faucibus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Ut porttitor nunc vel risus varius mollis. Suspendisse in laoreet quam. ");
            customer.setTestString3("\n" +
                    "\n" +
                    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis eget tempus sem, at condimentum tellus. Quisque tempus pellentesque eros, ullamcorper scelerisque sem luctus quis. Suspendisse nunc lorem, faucibus et scelerisque et, gravida non diam. Sed vulputate a orci euismod consectetur. Integer cursus vulputate porttitor. Vestibulum tortor eros, volutpat vitae pretium a, commodo eu sapien. Sed eget maximus urna. Sed vel quam vitae justo blandit pellentesque. Aenean eu rhoncus arcu. Quisque finibus tellus nunc, quis rhoncus sapien faucibus interdum.\n" +
                    "\n" +
                    "Donec tincidunt diam tincidunt justo aliquam, ac tincidunt libero dignissim. Etiam eros nunc, rhoncus sit amet efficitur vitae, dictum eget mi. Vestibulum mollis augue nisl. Mauris nec fermentum nisi, quis porttitor nulla. Nullam iaculis erat quis quam molestie, non pharetra purus faucibus. Fusce faucibus laoreet placerat. Maecenas vel tortor commodo augue cursus consequat. Sed molestie, purus vel pulvinar ultrices, lorem quam pretium nibh, eu ultricies dolor lacus et tellus. Aenean vel est dapibus, laoreet nisi nec, lacinia ex. Praesent ut leo tincidunt, porttitor diam ut, blandit felis. In in viverra quam, non consequat nulla.\n" +
                    "\n" +
                    "Phasellus id venenatis elit. Proin convallis nisl sed nisl ornare, non lacinia mauris porttitor. Vivamus sit amet leo at purus eleifend efficitur et eu dui. Sed at finibus elit, at feugiat nibh. In tincidunt vulputate nunc, pretium porta purus scelerisque a. Aenean a nulla leo. Nam a diam sit amet massa malesuada blandit vitae a urna. Quisque malesuada arcu et velit faucibus consectetur. Integer quis elementum nibh. Fusce ut purus in lacus finibus sodales. Quisque tincidunt id ipsum sit amet sollicitudin. Pellentesque sapien lorem, facilisis et sem eget, ultrices varius nibh. Mauris sed vehicula est. Phasellus sed nunc non nibh tincidunt vestibulum.\n" +
                    "\n" +
                    "Sed semper metus sed ante porta semper. Donec tristique sed turpis nec varius. Cras cursus eros tellus, at laoreet ante euismod porta. Cras hendrerit turpis eget nisi rhoncus, vel maximus orci blandit. Vivamus auctor sit amet tellus sed vestibulum. Pellentesque mi elit, gravida et urna quis, luctus convallis enim. Nulla blandit ante ut nisl maximus dignissim. Praesent venenatis odio in nisi fringilla ullamcorper non nec nulla. Curabitur ullamcorper nulla quis nulla faucibus porta. Curabitur lacinia justo mauris, non tincidunt lacus rhoncus quis. Nam consequat tempor massa ac tincidunt. Aenean dapibus elit nec nibh fermentum, vitae ultricies quam bibendum. Mauris interdum sem vel tincidunt faucibus.\n" +
                    "\n" +
                    "Nullam nibh urna, fringilla non condimentum id, fringilla nec nisi. Donec luctus orci sed leo ornare luctus. Mauris lobortis nisl neque, non lobortis lorem lacinia at. Aliquam placerat id nunc ut scelerisque. Aliquam ultricies, tellus ac varius vehicula, ante mauris dapibus arcu, eget rutrum risus enim vitae dui. Ut aliquam est varius tempus tempus. Ut eleifend, felis dignissim dignissim placerat, nisl nulla faucibus nunc, eget maximus tortor augue ut arcu. Nulla tempus odio ac justo ultricies placerat. Duis a auctor quam, quis sagittis libero. Sed sollicitudin magna in venenatis faucibus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Ut porttitor nunc vel risus varius mollis. Suspendisse in laoreet quam. ");
            customer.setTestString4("\n" +
                    "\n" +
                    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis eget tempus sem, at condimentum tellus. Quisque tempus pellentesque eros, ullamcorper scelerisque sem luctus quis. Suspendisse nunc lorem, faucibus et scelerisque et, gravida non diam. Sed vulputate a orci euismod consectetur. Integer cursus vulputate porttitor. Vestibulum tortor eros, volutpat vitae pretium a, commodo eu sapien. Sed eget maximus urna. Sed vel quam vitae justo blandit pellentesque. Aenean eu rhoncus arcu. Quisque finibus tellus nunc, quis rhoncus sapien faucibus interdum.\n" +
                    "\n" +
                    "Donec tincidunt diam tincidunt justo aliquam, ac tincidunt libero dignissim. Etiam eros nunc, rhoncus sit amet efficitur vitae, dictum eget mi. Vestibulum mollis augue nisl. Mauris nec fermentum nisi, quis porttitor nulla. Nullam iaculis erat quis quam molestie, non pharetra purus faucibus. Fusce faucibus laoreet placerat. Maecenas vel tortor commodo augue cursus consequat. Sed molestie, purus vel pulvinar ultrices, lorem quam pretium nibh, eu ultricies dolor lacus et tellus. Aenean vel est dapibus, laoreet nisi nec, lacinia ex. Praesent ut leo tincidunt, porttitor diam ut, blandit felis. In in viverra quam, non consequat nulla.\n" +
                    "\n" +
                    "Phasellus id venenatis elit. Proin convallis nisl sed nisl ornare, non lacinia mauris porttitor. Vivamus sit amet leo at purus eleifend efficitur et eu dui. Sed at finibus elit, at feugiat nibh. In tincidunt vulputate nunc, pretium porta purus scelerisque a. Aenean a nulla leo. Nam a diam sit amet massa malesuada blandit vitae a urna. Quisque malesuada arcu et velit faucibus consectetur. Integer quis elementum nibh. Fusce ut purus in lacus finibus sodales. Quisque tincidunt id ipsum sit amet sollicitudin. Pellentesque sapien lorem, facilisis et sem eget, ultrices varius nibh. Mauris sed vehicula est. Phasellus sed nunc non nibh tincidunt vestibulum.\n" +
                    "\n" +
                    "Sed semper metus sed ante porta semper. Donec tristique sed turpis nec varius. Cras cursus eros tellus, at laoreet ante euismod porta. Cras hendrerit turpis eget nisi rhoncus, vel maximus orci blandit. Vivamus auctor sit amet tellus sed vestibulum. Pellentesque mi elit, gravida et urna quis, luctus convallis enim. Nulla blandit ante ut nisl maximus dignissim. Praesent venenatis odio in nisi fringilla ullamcorper non nec nulla. Curabitur ullamcorper nulla quis nulla faucibus porta. Curabitur lacinia justo mauris, non tincidunt lacus rhoncus quis. Nam consequat tempor massa ac tincidunt. Aenean dapibus elit nec nibh fermentum, vitae ultricies quam bibendum. Mauris interdum sem vel tincidunt faucibus.\n" +
                    "\n" +
                    "Nullam nibh urna, fringilla non condimentum id, fringilla nec nisi. Donec luctus orci sed leo ornare luctus. Mauris lobortis nisl neque, non lobortis lorem lacinia at. Aliquam placerat id nunc ut scelerisque. Aliquam ultricies, tellus ac varius vehicula, ante mauris dapibus arcu, eget rutrum risus enim vitae dui. Ut aliquam est varius tempus tempus. Ut eleifend, felis dignissim dignissim placerat, nisl nulla faucibus nunc, eget maximus tortor augue ut arcu. Nulla tempus odio ac justo ultricies placerat. Duis a auctor quam, quis sagittis libero. Sed sollicitudin magna in venenatis faucibus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Ut porttitor nunc vel risus varius mollis. Suspendisse in laoreet quam. ");
            customer.setTestString5("\n" +
                    "\n" +
                    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis eget tempus sem, at condimentum tellus. Quisque tempus pellentesque eros, ullamcorper scelerisque sem luctus quis. Suspendisse nunc lorem, faucibus et scelerisque et, gravida non diam. Sed vulputate a orci euismod consectetur. Integer cursus vulputate porttitor. Vestibulum tortor eros, volutpat vitae pretium a, commodo eu sapien. Sed eget maximus urna. Sed vel quam vitae justo blandit pellentesque. Aenean eu rhoncus arcu. Quisque finibus tellus nunc, quis rhoncus sapien faucibus interdum.\n" +
                    "\n" +
                    "Donec tincidunt diam tincidunt justo aliquam, ac tincidunt libero dignissim. Etiam eros nunc, rhoncus sit amet efficitur vitae, dictum eget mi. Vestibulum mollis augue nisl. Mauris nec fermentum nisi, quis porttitor nulla. Nullam iaculis erat quis quam molestie, non pharetra purus faucibus. Fusce faucibus laoreet placerat. Maecenas vel tortor commodo augue cursus consequat. Sed molestie, purus vel pulvinar ultrices, lorem quam pretium nibh, eu ultricies dolor lacus et tellus. Aenean vel est dapibus, laoreet nisi nec, lacinia ex. Praesent ut leo tincidunt, porttitor diam ut, blandit felis. In in viverra quam, non consequat nulla.\n" +
                    "\n" +
                    "Phasellus id venenatis elit. Proin convallis nisl sed nisl ornare, non lacinia mauris porttitor. Vivamus sit amet leo at purus eleifend efficitur et eu dui. Sed at finibus elit, at feugiat nibh. In tincidunt vulputate nunc, pretium porta purus scelerisque a. Aenean a nulla leo. Nam a diam sit amet massa malesuada blandit vitae a urna. Quisque malesuada arcu et velit faucibus consectetur. Integer quis elementum nibh. Fusce ut purus in lacus finibus sodales. Quisque tincidunt id ipsum sit amet sollicitudin. Pellentesque sapien lorem, facilisis et sem eget, ultrices varius nibh. Mauris sed vehicula est. Phasellus sed nunc non nibh tincidunt vestibulum.\n" +
                    "\n" +
                    "Sed semper metus sed ante porta semper. Donec tristique sed turpis nec varius. Cras cursus eros tellus, at laoreet ante euismod porta. Cras hendrerit turpis eget nisi rhoncus, vel maximus orci blandit. Vivamus auctor sit amet tellus sed vestibulum. Pellentesque mi elit, gravida et urna quis, luctus convallis enim. Nulla blandit ante ut nisl maximus dignissim. Praesent venenatis odio in nisi fringilla ullamcorper non nec nulla. Curabitur ullamcorper nulla quis nulla faucibus porta. Curabitur lacinia justo mauris, non tincidunt lacus rhoncus quis. Nam consequat tempor massa ac tincidunt. Aenean dapibus elit nec nibh fermentum, vitae ultricies quam bibendum. Mauris interdum sem vel tincidunt faucibus.\n" +
                    "\n" +
                    "Nullam nibh urna, fringilla non condimentum id, fringilla nec nisi. Donec luctus orci sed leo ornare luctus. Mauris lobortis nisl neque, non lobortis lorem lacinia at. Aliquam placerat id nunc ut scelerisque. Aliquam ultricies, tellus ac varius vehicula, ante mauris dapibus arcu, eget rutrum risus enim vitae dui. Ut aliquam est varius tempus tempus. Ut eleifend, felis dignissim dignissim placerat, nisl nulla faucibus nunc, eget maximus tortor augue ut arcu. Nulla tempus odio ac justo ultricies placerat. Duis a auctor quam, quis sagittis libero. Sed sollicitudin magna in venenatis faucibus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Ut porttitor nunc vel risus varius mollis. Suspendisse in laoreet quam. ");
            customerRepository.save(customer);
        }

        return "hi";
    }
}
